apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-api
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deploy-api
    spec:
      containers:
        - image: 618118007154.dkr.ecr.us-east-1.amazonaws.com/flaskapi:__IMAGE__VALUE__
          name: deploy-api
          resources:
            requests:
              memory: "200Mi"
              cpu: "50m"
          ports:
            - containerPort: 5000
              name: deploy-api
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
          #Valores de variaveis de ambiente coletadas do Screts do Kubernetes
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: deploy-api-prd
                  key: dbhost
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: deploy-api-prd
                  key: dbuser
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: deploy-api-prd
                  key: dbpass
            - name: DB_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: deploy-api-prd
                  key: dbschema
            - name: APP_USER
              value: devops
            - name: APP_PASS
              valueFrom:
                secretKeyRef:
                  name: deploy-api-prd
                  key: apppass      