apiVersion: v1
kind: Service
metadata:
  name: deploy-api-service
  namespace: dev
  labels:
    app: deploy-api
spec:
  type: LoadBalancer
  selector:
      app: deploy-api
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
